"""
app_build.py

Usage:
    app_build.py [--major | --minor | --patch]
    app_build.py (-h | --help)

Options:
    -h --help   Show this screen.
    --major     Bump major version and reset minor and patch to 0.
    --minor     Bump minor version and reset patch to 0.
    --patch     Bump patch version.
"""

import datetime
import logging
import os
import re
import subprocess
import sys

from docopt import docopt

log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

APP_NAME = "RemoteProcess"
SCRIPT_NAME = os.path.join("src", "RemoteProcess.py")
ICON_PATH = os.path.join("assets", "RemoteProcess.ico")

BUILD_FILE = "app_build_number.txt"
VERSION_FILE = "app_version.txt"
YEAR_FILE = "app_year.txt"
SPEC_FILE = "RemoteProcess.spec"

DIST_PATH = os.path.join(os.getcwd(), "dist")
WORK_PATH = os.path.join(os.getcwd(), "build")

DEFAULT_VERSION = (1, 0, 0)
COMPANY_NAME = "Application Consulting Group, Inc."

# ---------------------------------------------------------------------------
# Version helpers
# ---------------------------------------------------------------------------

def read_version() -> tuple[int, int, int]:
    if not os.path.isfile(VERSION_FILE):
        log.warning("Version file not found; defaulting to %s.%s.%s", *DEFAULT_VERSION)
        return DEFAULT_VERSION

    with open(VERSION_FILE, "r") as f:
        content = f.read()

    match = re.search(r"FileVersion',\s*'(\d+)\.(\d+)\.(\d+)\.\d+'", content)
    if match:
        return int(match.group(1)), int(match.group(2)), int(match.group(3))

    log.warning("Could not parse version from %s; defaulting to %s.%s.%s", VERSION_FILE, *DEFAULT_VERSION)
    return DEFAULT_VERSION


def read_build() -> int:
    if not os.path.isfile(BUILD_FILE):
        return 1

    with open(BUILD_FILE, "r") as f:
        content = f.read().strip()

    try:
        build = int(content) + 1
    except ValueError:
        build = 1

    with open(BUILD_FILE, "w") as f:
        f.write(str(build) + "\n")

    return build


def bump_version(
    major: int, minor: int, patch: int, args: dict
) -> tuple[int, int, int]:
    if args["--major"]:
        return major + 1, 0, 0
    if args["--minor"]:
        return major, minor + 1, 0
    if args["--patch"]:
        return major, minor, patch + 1
    return major, minor, patch


# ---------------------------------------------------------------------------
# File writers
# ---------------------------------------------------------------------------

def write_version_file(major: int, minor: int, patch: int, build: int, year: int) -> None:
    content = f"""\
# UTF-8
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({major}, {minor}, {patch}, {build}),
    prodvers=({major}, {minor}, {patch}, {build}),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          u'040904B0',
          [StringStruct(u'CompanyName', u'{COMPANY_NAME}'),
           StringStruct(u'FileDescription', u'{APP_NAME}'),
           StringStruct(u'FileVersion', u'{major}.{minor}.{patch}.{build}'),
           StringStruct(u'InternalName', u'{APP_NAME}'),
           StringStruct(u'LegalCopyright', u'\\xa9 {year} {COMPANY_NAME}'),
           StringStruct(u'OriginalFilename', u'{APP_NAME}.exe'),
           StringStruct(u'ProductName', u'{APP_NAME}'),
           StringStruct(u'ProductVersion', u'{major}.{minor}.{patch}.{build}')])
      ]
    ),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
"""
    with open(VERSION_FILE, "w") as f:
        f.write(content)
    log.info("Wrote %s  (%d.%d.%d.%d)", VERSION_FILE, major, minor, patch, build)


def write_year_file(year: int) -> None:
    with open(YEAR_FILE, "w") as f:
        f.write(str(year) + "\n")
    log.info("Wrote %s  (%d)", YEAR_FILE, year)


def write_spec_file(major: int, minor: int, patch: int, build: int) -> None:
    base_dir = os.getcwd().replace("\\", "/")
    has_icon = os.path.isfile(ICON_PATH)
    icon_line = f"icon='{base_dir}/{ICON_PATH.replace(chr(92), '/')}'" if has_icon else "icon=None"

    datas = [
        f"('{base_dir}/{VERSION_FILE}', '.')",
        f"('{base_dir}/{YEAR_FILE}', '.')",
    ]
    datas_str = ",\n        ".join(datas)

    content = f"""\
# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by app_build.py — do not edit by hand.

block_cipher = None

a = Analysis(
    ['{base_dir}/{SCRIPT_NAME.replace(chr(92), "/")}'],
    pathex=['{base_dir}/src'],
    binaries=[],
    datas=[
        {datas_str}
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='{APP_NAME}',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version='{base_dir}/{VERSION_FILE}',
    {icon_line},
)
"""
    with open(SPEC_FILE, "w") as f:
        f.write(content)
    log.info("Wrote %s", SPEC_FILE)


# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------

def validate_requirements() -> bool:
    ok = True

    if not os.path.isfile(SCRIPT_NAME):
        log.error("Main script not found: %s", SCRIPT_NAME)
        ok = False

    for path in (DIST_PATH, WORK_PATH):
        os.makedirs(path, exist_ok=True)

    if not os.path.isfile(ICON_PATH):
        log.warning("Icon not found (%s) — building without icon", ICON_PATH)

    return ok


def build_executable() -> bool:
    cmd = [
        sys.executable, "-m", "PyInstaller",
        SPEC_FILE,
        "--distpath", DIST_PATH,
        "--workpath", WORK_PATH,
        "--clean",
        "--noconfirm",
    ]
    log.info("Running: %s", " ".join(cmd))
    result = subprocess.run(cmd)
    return result.returncode == 0


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s  %(levelname)-8s  %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )

    args = docopt(__doc__)

    if not validate_requirements():
        sys.exit(1)

    major, minor, patch = read_version()
    major, minor, patch = bump_version(major, minor, patch, args)
    build = read_build()
    year = datetime.date.today().year

    log.info("Building %s  v%d.%d.%d.%d", APP_NAME, major, minor, patch, build)

    write_version_file(major, minor, patch, build, year)
    write_year_file(year)
    write_spec_file(major, minor, patch, build)

    if build_executable():
        log.info("Build succeeded → dist/%s.exe", APP_NAME)
    else:
        log.error("Build failed")
        sys.exit(1)


if __name__ == "__main__":
    main()
