name: remoteexecute
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.11
  - pip
  - pip:
      - TM1py==2.1
      - docopt==0.6.2
      - pyinstaller==6.13.0
      - cryptography>=42.0.0
